### ISSUE TITLE
集成里添加报错

### ISSUE THREAD

**Issue by 877723797** [rxwen/homeassistant-terncy-component#1]
错误
无法加载配置向导

**Comment by rxwen** [comment]
你好。谢谢反馈。

请查询一下 home assistant的版本信息。

并可用下面的方面获取一下插件的运行日志。

调试

启用及查看小燕插件日志的方法

在 home assistant 配置目录下的 configuration.yaml 文件中添加以下内容：

default_config:

logger:
  default: info
  logs:
    homeassistant.components.terncy: info

重启 home assistant 后，可在 http://{ip_of_home_assistant}:8123/config/logs 页查看日志。如果通过 docker 运行 home assistant，也可用 docker logs -f --tail 0 {docker_instantce_name} 命令查看。
