### ISSUE TITLE
建議增加牆壁開關的按鈕action功能

### ISSUE THREAD

**Issue by andywei1996** [rxwen/homeassistant-terncy-component#11]
如同小燕在家app中的可編程開關，希望這個功能也能被加入Home assistant。

**Comment by rxwen** [comment]
这个功能在小燕的app中编辑也可以的吧。
从配对过程来说，也依赖小燕的app授权，它的存在还是必要的。

**Comment by rxwen** [comment]
@andywei1996 最新的 1.0.19 版本可以试试看，开放了此功能。
