### ISSUE TITLE
能否支持一下小燕的门磁开关

### ISSUE THREAD

**Issue by Mingmingmew** [rxwen/homeassistant-terncy-component#12]
我看我的门磁开关状态显示的是unsupported 然后我布防跟撤防 好像也是没有任何状态变化的

**Comment by rxwen** [comment]
请问你的ha是什么版本？

**Comment by Mingmingmew** [comment]
## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v8+
arch | aarch64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.3
Stage | running
Available Repositories | 1101
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.14
disk_total | 116.9 GB
disk_used | 15.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Samba share (9.5.1), Node-RED (11.1.1), Studio Code Server (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 17
views | 6
mode | storage

</details>

**Comment by Mingmingmew** [comment]
刚刚升级到最新版 好像直接所有的实体全部状态全部变成了 unavailable 不单单是门磁了

**Comment by wuwin1993** [comment]
我接入home assist后也显示小燕的门磁传感器不可用
![image](https://user-images.githubusercontent.com/109844411/180648965-eaf4582e-9d7c-4997-9533-d74a14b4ad8b.png)
我的ha是2022.7.6

**Comment by wuwin1993** [comment]
![image](https://user-images.githubusercontent.com/109844411/180649011-e203dfa4-43d4-4c75-80ee-d96c5e4cda29.png)

**Comment by wuwin1993** [comment]
重启几次ha后 门磁可用 但是门窗自带的温度感应又不可用了

**Comment by wuwin1993** [comment]
![image](https://user-images.githubusercontent.com/109844411/181772534-4d63e469-1565-4a0a-8a17-e6ba307b38e3.png)
多次删除集成并添加 门磁和人体感应器的开关、人体感应功能和温度、亮度感应功能只能创建其中一个实体。比如门磁如果开门感应可以使用，那亮度感应就不能用

**Comment by rxwen** [comment]
1.0.21 版本优化解决
