### ISSUE TITLE
Support porting light groups

### ISSUE THREAD

**Issue by hzxa21** [rxwen/homeassistant-terncy-component#16]

**Comment by hzxa21** [comment]
To give more contexts on this, this plugin currently only support porting a single light device to homeassistant (i.e. hass). However, when using the terncy product, we normally won't just use a single light device and the most common practice is to group lights in an area into a group and turn on super sync (i.e. “超级同步”).

This is truly a big gap. In other words, when I was trying to use terncy's produce in hass via this plugin, I need to manually create all the light groups. Not to mention that the super sync feature is lacking. It is troublesome especially in my cases since I have 100+ terncy devices.

IMO, I don't think it will be super hard to support porting light groups. I am willing to contribute as a community developer and help if needed.

cc @rxwen

**Comment by rxwen** [comment]
Hi Patrick,

Thanks for trying to give a hand on this project. It's definitely a great support, and it's welcome.

My idea is this project will be providing the basic device information to the hass platform, user can take advantage of the functions in hass itself to create groups, scenes, autoamtions, etc. The advanced and complex concepts ideas of terncy system is not mandatory part of integration.

You can feel free to create a PR and submit. The basic idea is to start an additional get entity request here:
https://github.com/rxwen/homeassistant-terncy-component/blob/main/terncy/__init__.py#L353 , passing "devicegroup" as argument.

Feel free to let me know if in and doubt.
