### ISSUE TITLE
是否可以增加对感应开关左右动作传感器的支持（Wish to add the left and right motion sensor support for the awareness switch）

### ISSUE THREAD

**Issue by MichaelRow** [rxwen/homeassistant-terncy-component#2]
目前在Home Assistant里感应开关的左右动作传感器被当做一个动作传感器，无法区分动作是由哪个传感器触发的，希望能增加对此的支持。另外，如果可以再增加光照度传感器的支持就再好不过了。

The left and right motion sensors are treated as one motion sensor in the Home Assistant, so it can't figure out the sensor which triggers. Adding the left and right motion support would be very thankful.
By the way it would be nice to add the light sensor support.

**Comment by rxwen** [comment]
谢谢反馈。
我会看一下这个功能的。

**Comment by MichaelRow** [comment]
谢谢。
问下这个项目是personal还是official？

**Comment by rxwen** [comment]
这是个personal项目，属于个人爱好。

**Comment by Polymerkid0** [comment]
Also, wish to see the support of light level of the motion sensor. Thx.

**Comment by rxwen** [comment]
1.0.21 版本支持
