### ISSUE TITLE
添加时显示请填写所有必填字段，无法提交

### ISSUE THREAD

**Issue by denisqi** [rxwen/homeassistant-terncy-component#20]
尝试更改家庭中心名字，改成中英文都不可以

![1](https://user-images.githubusercontent.com/118659778/202966271-33875008-f695-45cd-a732-f118b57d7a97.jpg)

**Comment by rxwen** [comment]
请问ha的版本是多少？
ha的日志里是否有出现什么错误信息？

**Comment by gg159753** [comment]
这个问题我在docker上的ha遇到过  是因为桥接模式网络的问题 ha发现不了本地网络里设备。

**Comment by denisqi** [comment]
> 这个问题我在docker上的ha遇到过 是因为桥接模式网络的问题 ha发现不了本地网络里设备。

我也是在docker ha里遇到的，请问您是怎么解决的？

**Comment by gg159753** [comment]
> > 这个问题我在docker上的ha遇到过 是因为桥接模式网络的问题 ha发现不了本地网络里设备。
> 
> 我也是在docker ha里遇到的，请问您是怎么解决的？

把桥接模式改成host模式就搞定了

**Comment by kit294** [comment]
不是docker 上的ha 可以如何解決?
