### ISSUE TITLE
Would air conditioner VG01 be supported?

### ISSUE THREAD

**Issue by unijiang** [rxwen/homeassistant-terncy-component#26]
Would air conditioner VG01be supported?
什么时候可以支持中央空调VG01？

**Comment by rxwen** [comment]
The support for it is on the roadmap, the date has not yet been fixed.

**Comment by rxwen** [comment]
It's supported in v1.0.31

**Comment by unijiang** [comment]
Thanks a lot.

- Wei
________________________________
发件人: rxwen ***@***.***>
发送时间: 2023年11月6日 15:27
收件人: rxwen/homeassistant-terncy-component ***@***.***>
抄送: unijiang ***@***.***>; Author ***@***.***>
主题: Re: [rxwen/homeassistant-terncy-component] Would air conditioner VG01 be supported? (Issue #26)


It's supported in v1.0.31

―
