### ISSUE TITLE
大神你好  

### ISSUE THREAD

**Issue by linqiyi071** [rxwen/homeassistant-terncy-component#3]
为什么我的添加网关以后会重复添加

**Comment by rxwen** [comment]
你好，

请问你说的“重复添加”具体指的是什么现象？能否详细描述一下。
并可以通过 https://github.com/rxwen/homeassistant-terncy-component/blob/main/README.zh-cn.md 这个文章最底部的方式，获取一份运行日志看一下是什么情况。

**Comment by MichaelRow** [comment]
![image](https://user-images.githubusercontent.com/7512027/127607500-fc404b17-a29f-4140-a5a5-7cfe28f9949e.png)
![image](https://user-images.githubusercontent.com/7512027/127607965-3cfdf87d-fc27-4f08-b9ee-06cef79fcd15.png)

可能和我出现的这两个问题类似，每隔一段时间会有通知发现新设备。
[ha.log](https://github.com/rxwen/homeassistant-terncy-component/files/6905382/ha.log)

**Comment by rxwen** [comment]
这期间 ha 是否有重启过？
有没发现，重复出现家庭中心设备，是不是和某个特定操作有关呢？

**Comment by MichaelRow** [comment]
<img width="1792" alt="截屏2021-07-30 下午4 28 22" src="https://user-images.githubusercontent.com/7512027/127625412-73d0303a-19ea-490d-81c5-c4f9a829793b.png">

提示可配置的设备会越来越多。重启是更改log的level，搜索设备感觉是间歇性的。之前的HA版本是2021.6.4，在集成页最多只会有一个可配置设备；今天更新到2021.7.2，可配置设备会越来越多。

所以和HA版本相关，还可能和集成的插件相关。

因为这个时间点家里没人，也没自动化会触发，自动化除了一个是node-red，其他都是HomeKit。

**Comment by MichaelRow** [comment]
Host是群晖，HA安装在docker

**Comment by rxwen** [comment]
我尝试一下这个版本看看

**Comment by angus9487** [comment]
2021.7.1版本同样问题，添加完设备后把config_flow.py最下面的async_step_zeroconf方法删了之后，重启ha就不会一直刷新设备了

**Comment by rxwen** [comment]
应该是ha修改了设备对象的唯一id算法导致的。我看看。

**Comment by rxwen** [comment]
这个问题在 https://github.com/rxwen/homeassistant-terncy-component/commit/1d7c61816915be8f0295f7f929ce3b20ab3e5b3d 中fix了。
已经发布 1.0.8 版本。请尝试一下。

**Comment by rxwen** [comment]
在 ha 2021.9.0 版本中验证通过。
