### ISSUE TITLE
添加集成后可以读取状态，不能控制

### ISSUE THREAD

**Issue by ThanYi1** [rxwen/homeassistant-terncy-component#31]
刚添加完集成时是可以在ha上控制的，状态读取也正常，没多久就只能读取状态了，你们有这种情况吗？怎么处理

**Comment by rxwen** [comment]
能否提供状态不对时，ha的日志看看。

**Comment by ThanYi1** [comment]
> 能否提供状态不对时，ha的日志看看。

昨天重启ha后目前小燕集成正常，若稍晚出现异常再与您联系

**Comment by xzshow** [comment]
22版本的如果路由重启后再不可控了，重载集成后也不可控了，非要重加入集成，并且重启启动虚拟机（我群晖虚拟机装的）不会弄日志呀
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 添加集成后可以读取状态，不能控制 (Issue #31)





  
能否提供状态不对时，ha的日志看看。
  
昨天重启ha后目前小燕集成正常，若稍晚出现异常再与您联系

**Comment by ThanYi1** [comment]
> 

要的日志应该是集成-找到小燕卡片，右下角三个点打开有调试日志

**Comment by angus9487** [comment]
嗯，更新HA后也遇到了这个问题，无法控制了，操作了几下看了下好像没有日志，回退到2022.6.7版本就好了
