### ISSUE TITLE
支持旋钮的旋转事件

### ISSUE THREAD

**Issue by andy741217** [rxwen/homeassistant-terncy-component#4]
開關被判斷為實體是light.
旋鈕開關有機會被整合進去嗎?

**Comment by andy741217** [comment]
旋鈕  我有加入過Z2M 自己用exploer 做過  搞成可以選轉 數字可調~但太難用了!
看能不能把 選轉的功能加進去~讓他可以控制窗簾類

**Comment by rxwen** [comment]
能否提供一个代码链接参考一下？
我想了解一下是如何暴露旋转事件给外部使用的。
