### ISSUE TITLE
是否有支持旋钮开关旋钮操作的计划

### ISSUE THREAD

**Issue by lifetimr** [rxwen/homeassistant-terncy-component#40]
请问一下是否有支持旋钮开关旋钮操作的计划

**Comment by Necroneco** [comment]
局域网协议里目前只有 rotation 事件，不能区分左右和角度。
可以看一下PR #43

**Comment by lifetimr** [comment]
> 局域网协议里目前只有 rotation 事件，不能区分左右和角度。 可以看一下PR #43

大佬，收到局域网协议的说明书后，能区分左右和角度么？

**Comment by Necroneco** [comment]
> 大佬，收到局域网协议的说明书后，能区分左右和角度么？

没的。这设备我有，我实测过的

**Comment by lifetimr** [comment]
https://youtu.be/JJgzS9UEadM
大佬，我看到之前已经关闭的问题终，有提到使用的mqtt使得旋钮可以增加左右旋转等方式，不知道在现有情况下可以参考之后直接集成么？感谢大佬的辛苦解答和帮助。

**Comment by Necroneco** [comment]
> https://youtu.be/JJgzS9UEadM 大佬，我看到之前已经关闭的问题终，有提到使用的mqtt使得旋钮可以增加左右旋转等方式，不知道在现有情况下可以参考之后直接集成么？感谢大佬的辛苦解答和帮助。

这个集成是基于网关的局域网协议接入的，不是通过zigbee和设备通信的。目前局域网协议里面没有旋转方向和角度的信息，可以 @rxwen 看看能不能加上相关字段。

目前有需求的话，可以先试试z2m接入吧

**Comment by rxwen** [comment]
对的，这个功能在小燕网关里无法使用。只能通过zigbee 层面对接的方式才可以用的。
Regards,
Ruixiong Wen


Necroneco ***@***.***>于2023年11月3日 周五12:45写道：

**Comment by xzshow** [comment]
能不能识别到房间呀，设备多了，小燕APP分好房间，到HA中全部要手动，100多个设备搞死人







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2023年11月3日 12:45
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
https://youtu.be/JJgzS9UEadM 大佬，我看到之前已经关闭的问题终，有提到使用的mqtt使得旋钮可以增加左右旋转等方式，不知道在现有情况下可以参考之后直接集成么？感谢大佬的辛苦解答和帮助。
  
这个集成是基于网关的局域网协议接入的，不是通过zigbee和设备通信的。目前局域网协议里面没有旋转方向和角度的信息，可以 @rxwen 看看能不能加上相关字段。
 
目前有需求的话，可以先试试z2m接入吧

**Comment by Necroneco** [comment]
> 能不能识别到房间呀，设备多了，小燕APP分好房间，到HA中全部要手动，100多个设备搞死人 发自我的iPhone

你为啥发在这个 issue 里。。

我记得房间支持之前已经加上了 #46 ，可能需要更新网关固件，你现在的网关是什么版本？

**Comment by xzshow** [comment]
网关两个 &nbsp; 一个带音频，一个不带都是 3.1.99



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2023年11月6日 17:04
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
能不能识别到房间呀，设备多了，小燕APP分好房间，到HA中全部要手动，100多个设备搞死人 发自我的iPhone
  
你为啥发在这个 issue 里。。
 
我记得房间支持之前已经加上了 #46 ，可能需要更新网关固件，你现在的网关是什么版本？

**Comment by xzshow** [comment]
因为目前上不了G网站，只能回邮件





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2023年11月6日 17:04
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
能不能识别到房间呀，设备多了，小燕APP分好房间，到HA中全部要手动，100多个设备搞死人 发自我的iPhone
  
你为啥发在这个 issue 里。。
 
我记得房间支持之前已经加上了 #46 ，可能需要更新网关固件，你现在的网关是什么版本？

**Comment by Necroneco** [comment]
> 因为目前上不了G网站，只能回邮件 发自我的iPhone

要不 更新一下？

**Comment by xzshow** [comment]
更新网关还是插件呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2023年11月6日 19:10
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
因为目前上不了G网站，只能回邮件 发自我的iPhone
  
要不 更新一下？

**Comment by Necroneco** [comment]
> 更新网关还是插件呀 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Necroneco ***@***.***&gt; 发送时间: 2023年11月6日 19:10 收件人: rxwen/homeassistant-terncy-component ***@***.***&gt; 抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 因为目前上不了G网站，只能回邮件 发自我的iPhone 要不 更新一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

网关。（插件至少到1.0.25以上吧大概

**Comment by xzshow** [comment]
网关好像没更新了吧？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2023年11月6日 19:14
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
更新网关还是插件呀 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Necroneco @.&gt; 发送时间: 2023年11月6日 19:10 收件人: rxwen/homeassistant-terncy-component @.&gt; 抄送: xzshow @.&gt;, Comment @.&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 因为目前上不了G网站，只能回邮件 发自我的iPhone 要不 更新一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
网关。（插件至少到1.0.25以上吧大概

**Comment by Necroneco** [comment]
> 网关好像没更新了吧？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Necroneco ***@***.***&gt; 发送时间: 2023年11月6日 19:14 收件人: rxwen/homeassistant-terncy-component ***@***.***&gt; 抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 更新网关还是插件呀 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Necroneco @.&gt; 发送时间: 2023年11月6日 19:10 收件人: rxwen/homeassistant-terncy-component @.&gt; 抄送: xzshow @.&gt;, Comment @.&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 因为目前上不了G网站，只能回邮件 发自我的iPhone 要不 更新一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 网关。（插件至少到1.0.25以上吧大概 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

开发版，3.2.8

**Comment by xzshow** [comment]
开发版本的没问题吧？现在小燕情况又不明，要是开发版有问题，又不知道怎么回退




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 晚上7:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
网关好像没更新了吧？ 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Necroneco @.&gt; 发送时间: 2023年11月6日 19:14 收件人: rxwen/homeassistant-terncy-component @.&gt; 抄送: xzshow @.&gt;, Comment @.&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 更新网关还是插件呀 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Necroneco @.&gt; 发送时间: 2023年11月6日 19:10 收件人: rxwen/homeassistant-terncy-component @.&gt; 抄送: xzshow @.&gt;, Comment @.&gt; 主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40) 因为目前上不了G网站，只能回邮件 发自我的iPhone 要不 更新一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 网关。（插件至少到1.0.25以上吧大概 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
开发版，3.2.8

**Comment by Necroneco** [comment]
> 开发版本的没问题吧？现在小燕情况又不明，要是开发版有问题，又不知道怎么回退

那就没办法了，旧版本网关没有发送房间信息

**Comment by xzshow** [comment]
您是开发版的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
开发版本的没问题吧？现在小燕情况又不明，要是开发版有问题，又不知道怎么回退
  
那就没办法了，旧版本网关没有发送房间信息

**Comment by Necroneco** [comment]
> 您是开发版的吗？

嗯 是的

**Comment by xzshow** [comment]
请教下，升级了要重在HA中添加网关？还是直接将原来文件覆盖重启就行了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
您是开发版的吗？
  
嗯 是的

**Comment by Necroneco** [comment]
> 请教下，升级了要重在HA中添加网关？还是直接将原来文件覆盖重启就行了。

升级网关和HA没关系。
升级HA的集成..大概就是你说的覆盖重启吧。
不用重新添加网关。

**Comment by xzshow** [comment]
而且我发现200多元的那个网关没有新固件，只有有AIRPLAY的那个网关才有你说 的3.2.8版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
请教下，升级了要重在HA中添加网关？还是直接将原来文件覆盖重启就行了。
  
升级网关和HA没关系。
 升级HA的集成..大概就是你说的覆盖重启吧。
 不用重新添加网关。

**Comment by xzshow** [comment]
也就是说我两个网关，有一个有3.2.8版本的固体，有一个没有，两个网关不是一样型号的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
请教下，升级了要重在HA中添加网关？还是直接将原来文件覆盖重启就行了。
  
升级网关和HA没关系。
 升级HA的集成..大概就是你说的覆盖重启吧。
 不用重新添加网关。

**Comment by Necroneco** [comment]
> 而且我发现200多元的那个网关没有新固件，只有有AIRPLAY的那个网关才有你说 的3.2.8版本

有的，可能等等就有了

**Comment by xzshow** [comment]
那我先升级另一个网关试下了，确定有吗？兄弟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
而且我发现200多元的那个网关没有新固件，只有有AIRPLAY的那个网关才有你说 的3.2.8版本
  
有的，可能等等就有了

**Comment by Necroneco** [comment]
> 那我先升级另一个网关试下了，确定有吗？兄弟

有的，我用的就是那个便宜的型号。而且俩网关版本不一样也没啥大关系吧大概

**Comment by xzshow** [comment]
我升级了还是没有房间




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
那我先升级另一个网关试下了，确定有吗？兄弟
  
有的，我用的就是那个便宜的型号。而且俩网关版本不一样也没啥大关系吧大概

**Comment by Necroneco** [comment]
> 我升级了还是没有房间

HA里的集成版本是多少？重载一下试试？

**Comment by xzshow** [comment]
不知道啥子 原因，我将网关和HA都 升级到最新 的，还是没有房间出来，我在HA中删除了网关才添加也是没有


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
我升级了还是没有房间
  
HA里的集成版本是多少？重载一下试试？

**Comment by Necroneco** [comment]
> 不知道啥子 原因，我将网关和HA都 升级到最新 的，还是没有房间出来，我在HA中删除了网关才添加也是没有

噢 有个问题刚想起来，小燕默认创建的那些房间的名字，拉不到。（这个问题我去反馈一下）
你看看是所有房间都没有还是自己另外命名的房间是有的？

**Comment by xzshow** [comment]
我没太明白您 的意思 ，我是在HA中创建的房间，跟小燕APP中是一样名字




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 晚上9:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
不知道啥子 原因，我将网关和HA都 升级到最新 的，还是没有房间出来，我在HA中删除了网关才添加也是没有
  
噢 有个问题刚想起来，小燕默认创建的那些房间的名字，拉不到。（这个问题我去反馈一下）
 你看看是所有房间都没有还是自己另外命名的房间是有的？

**Comment by xzshow** [comment]
您 的意思是说我不能先在HA中创建房间吗？如果 这样我还有其它的品牌设备






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rxwen/homeassistant-terncy-component"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rxwen/homeassistant-terncy-component] 是否有支持旋钮开关旋钮操作的计划 (Issue #40)





  
不知道啥子 原因，我将网关和HA都 升级到最新 的，还是没有房间出来，我在HA中删除了网关才添加也是没有
  
噢 有个问题刚想起来，小燕默认创建的那些房间的名字，拉不到。（这个问题我去反馈一下）
 你看看是所有房间都没有还是自己另外命名的房间是有的？

**Comment by Necroneco** [comment]
> 您 的意思是说我不能先在HA中创建房间吗？如果 这样我还有其它的品牌设备

不 不是这个意思，我是说 小燕app里默认会创建一些房间（大概有八九个），这几个房间的名字暂时没同步过来。其他你另外自定义的房间名字应该是同步了的的。
