### ISSUE TITLE
TERNCY-WS01: Have all buttons under one device?

### ISSUE THREAD

**Issue by diegocjorge** [rxwen/homeassistant-terncy-component#41]
For TERNCY-WS01 (Kiryo) wall switch, would it be possible to have all the buttons under one device? 
For exemple: Device is switch 8cf(..)48-00 and it has 4 entities 8cf(..)48-01, 8cf(..)48-02, 8cf(..)48-03, and 8cf(..)48-04
Having every button as its own device makes it a lot harder to create automations and makes it impossible to use it with Switch Manager integration (https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/)

**Comment by rxwen** [comment]
Would you please try [v1.0.31](https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.31) ?
