### ISSUE TITLE
添加集成显示错误 无法加载配置向导: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Maozhenlei** [rxwen/homeassistant-terncy-component#49]
错误
无法加载配置向导: 500 Internal Server Error Server got itself in trouble

HAOS 2023.10.5

**Comment by Necroneco** [comment]
试试重新安装集成

**Comment by Maozhenlei** [comment]
> 试试重新安装集成

试了很多方法，比如重装集成，把HA备份恢复到另一台虚拟机……都失败了，挺愁人的。
2023.4可以正常运行，但升级2023.10.5就报错了。
但是在一个全新的HA里，添加集成又是可以成功的，愁死了。

**Comment by Necroneco** [comment]
这还挺费解的，你用的是OS吗？日志里有没有什么别的更详细的信息？

**Comment by Maozhenlei** [comment]
> 这还挺费解的，你用的是OS吗？日志里有没有什么别的更详细的信息？

挺尴尬的 发现是因为之前在custom_components下面，复制出来了一个“terncy 副本"的文件夹导致的，删除该文件夹后就都好了。。抱歉=-=

**Comment by seanzou0** [comment]
> > 这还挺费解的，你用的是OS吗？日志里有没有什么别的更详细的信息？
> 
> 挺尴尬的 发现是因为之前在custom_components下面，复制出来了一个“terncy 副本”的文件夹导致的，删除该文件夹后就都好了。。抱歉=-=

我遇到了同样的一个问题！但是我没有副本问题，如何解决呀
