### ISSUE TITLE
安装时无下拉窗

### ISSUE THREAD

**Issue by zxq321zxq** [rxwen/homeassistant-terncy-component#5]
![image](https://user-images.githubusercontent.com/50660883/140630832-3f43a396-fa58-4ca2-9f79-09f7152fea62.png)

Home Assistant 版本2021.11.0.dev20211027

**Comment by zxq321zxq** [comment]
docker安装的homeassistant

**Comment by rxwen** [comment]
谢谢反馈。
我会检查一下和这个版本的兼容性

**Comment by rxwen** [comment]
使用 ha  2021.11.0 的docker镜像，没有重现这个问题。
注意到你用的 ha  是 dev 版本，能否切换到正式版本试试看？
@zxq321zxq

**Comment by zxq321zxq** [comment]
使用正式版就可以了
