### ISSUE TITLE
小燕门磁温度正常显示，开合状态未知

### ISSUE THREAD

**Issue by powjie** [rxwen/homeassistant-terncy-component#50]
之前homeassistant可以正常显示开合状态，不知道什么时候变未知了，从1.0.25，删除了custom_components/terncy，换成了1.035的terncy，还是未知。但是小燕在家app和HomeKit里是正常的，请问怎么处理

**Comment by Necroneco** [comment]
1.0.25可用吗?

**Comment by powjie** [comment]
> 1.0.25可用吗？

1.0.25曾经可用，就某个时间开始不可用了

**Comment by Necroneco** [comment]
那你看是否方便提供一下日志看看

在集成页面点击 “启用调试日志”，然后重载一下集成，然后开合一下门磁，再点击 “禁用调试日志”

**Comment by rxwen** [comment]
我这边的门磁也是显示状态不对。我在本地调试分析下看看。

**Comment by rxwen** [comment]
Fix in v1.0.36
