### ISSUE TITLE
HA重启后集成不可用

### ISSUE THREAD

**Issue by lifetimr** [rxwen/homeassistant-terncy-component#52]
HA重启后会出现实体不可用的情况，日志中未找到对应报错，不知道大佬们有没有相应的问题，多次重启后才能恢复，且问题随机出现。

**Comment by lifetimr** [comment]
> 是最新版本么? 单独重载集成有用么?

haos 11.3版本，单独重载集成没有作用，当前发现只能多次重启，尝试过删除core文件下的实体id信息，依旧无效

**Comment by Necroneco** [comment]
> > 是最新版本么? 单独重载集成有用么?
> 
> haos 11.3版本，单独重载集成没有作用，当前发现只能多次重启，尝试过删除core文件下的实体id信息，依旧无效

集成版本是 1.0.36 ？

可以尝试参考[这里](https://github.com/rxwen/homeassistant-terncy-component/blob/main/README.zh-cn.md#%E8%B0%83%E8%AF%95)打开一下调试日志，看看有没有更多信息

**Comment by rxwen** [comment]
https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.41
如果还有问题，请尝试这个版本
