### ISSUE TITLE
请问精卫DIM002如何在小燕APP里调节电流呢？

### ISSUE THREAD

**Issue by 1043717432** [rxwen/homeassistant-terncy-component#53]
请问精卫DIM002如何在小燕APP里调节电流呢？

**Comment by rxwen** [comment]
只需要通过局域网就可以工作的，不依赖云服务器。
色温的问题在上个版本是好的吗？看最近的提交应该没改过这部分。

Regards,
Ruixiong Wen


1043717432 ***@***.***>于2023年12月16日 周六16:16写道：
