### ISSUE TITLE
无法加载配置向导: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by seanzou0** [rxwen/homeassistant-terncy-component#54]
通过HACS自定义安装后，添加集成失败！1.036
无法加载配置向导: 500 Internal Server Error Server got itself in trouble

**Comment by Necroneco** [comment]
我以前遇到过这种错，一般要么是网络问题（代理没关或者没配置好），要么是集成实际没安装成功（可以检查一下 config/custom_components/terncy 里面(用samba或者ssh) 进去看看文件是不是完整）

**Comment by seanzou0** [comment]
> 我以前遇到过这种错，一般要么是网络问题（代理没关或者没配置好），要么是集成实际没安装成功（可以检查一下 config/custom_components/terncy 里面(用samba或者ssh) 进去看看文件是不是完整）

您现在还是可以正常使用该插件吗？啊，文件没问题，我反复好多次了，网络也正常的

**Comment by Necroneco** [comment]
嗯，我可以正常用，顺便一提我配置的时候是用自动发现的

**Comment by rxwen** [comment]
Ha的日志有显示更详细的错误信息吗？


Necroneco ***@***.***>于2023年12月26日 周二16:07写道：

**Comment by seanzou0** [comment]
[
<img width="439" alt="c6be1a8181547d4400ecf19ccfcdf637" src="https://github.com/rxwen/homeassistant-terncy-component/assets/21035671/2b8cafa8-dc7a-4e84-a6d3-7ee0b0d5f5ad">
](url)
<img width="367" alt="f0fe7c26fa822e330c992eaa10f6187f" src="https://github.com/rxwen/homeassistant-terncy-component/assets/21035671/e32949d7-0862-4064-8b4d-f1025c4db23c">

**Comment by seanzou0** [comment]
> 嗯，我可以正常用，顺便一提我配置的时候是用自动发现的

方便给个联系方式吗？我这实在搞不定，家里一百多个小燕设备，加不了，哎

**Comment by Necroneco** [comment]
> [ <img alt="c6be1a8181547d4400ecf19ccfcdf637" width="439" src="https://private-user-images.githubusercontent.com/21035671/292879995-2b8cafa8-dc7a-4e84-a6d3-7ee0b0d5f5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDA1MTEsIm5iZiI6MTcwMzYwMDIxMSwicGF0aCI6Ii8yMTAzNTY3MS8yOTI4Nzk5OTUtMmI4Y2FmYTgtZGM3YS00ZTg0LWE2ZDMtN2VlMGIwZDVmNWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNGIwNjBmMjc2Y2Y0NmY2ZWU3OWVjYWU4ZmY2MDIyMzA2ZWU4NjY3ZTE3YzE3ZWM2ZGZkM2I3MzM4MDdhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RTKq5KrkLkfiwGtXUDr9QDYKwA1nksuBxjZeqwtUYF8"> ](url) <img alt="f0fe7c26fa822e330c992eaa10f6187f" width="367" src="https://private-user-images.githubusercontent.com/21035671/292880017-e32949d7-0862-4064-8b4d-f1025c4db23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDA1MTEsIm5iZiI6MTcwMzYwMDIxMSwicGF0aCI6Ii8yMTAzNTY3MS8yOTI4ODAwMTctZTMyOTQ5ZDctMDg2Mi00MDY0LThiNGQtZjEwMjVjNGRiMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTMyZmU4OWY4MDc3OTA5ZGMzNzA1NDY0YjNkYTYzMDY1OGFlYzQ1NGEyYzlhZWI3OTcwMDFiNGFiZDFjMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRFFMvVCl_rSKJzz6h7gAmVLFIy7K-gJ1A2bV99Vj7E">

我直接添加集成也是这样的，要等它自动发现。这边现在看上去感觉怪怪的 其实只是因为它是个空列表。

至于为什么没能自动发现，可能还是要检查一下内网，比如你的HA是怎么搭的？有没有host网络？

**Comment by Necroneco** [comment]
> > 嗯，我可以正常用，顺便一提我配置的时候是用自动发现的
> 
> 方便给个联系方式吗？我这实在搞不定，家里一百多个小燕设备，加不了，哎

你可以发我邮件

**Comment by kingfr1994** [comment]
我也遇到了相同的问题，不管是从hacs里面安装还是自行下载解压安装，始终无法自动发现

**Comment by kingfr1994** [comment]
奏折已收到,我会提醒主人及时批阅的~
