### ISSUE TITLE
透天環境，三樓網關一陣子會無回應

### ISSUE THREAD

**Issue by uho886** [rxwen/homeassistant-terncy-component#57]
請問是否有人遇到一段時間後，網關在ha沒有回應,需要重新載入，實體才能用（使用環境有五個家庭中心，其中2/3/4樓有做多網關融合。）目前只有遇到三樓這組有問題
![IMG_0491](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/4dad46cb-b2df-413f-97c7-6ec78437eb8a)
![IMG_0492](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/4e59876f-9661-4b21-b5a6-f78d3074e59a)
![IMG_0493](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/c2fddf66-65bf-4465-929b-9a69dd1e46af)
![IMG_0494](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/95eaf4ac-923d-43c7-b87c-943443cb1643)
![IMG_0495](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/badbae37-5902-4061-9f18-81177814ca17)
![IMG_0496](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/e97d9f0c-0eef-4ec1-96ff-6743343cfc69)
![IMG_0497](https://github.com/rxwen/homeassistant-terncy-component/assets/136594428/ac440aaf-8585-4b73-9192-afda8e0652b4)

**Comment by Necroneco** [comment]
有遇到过类似问题，需要在HA重载集成才能好，不过出现频率不高（可能几周一次），暂时还没找到原因。

我会开日志关注一下，看看下次出现的时候能不能找到线索

**Comment by uho886** [comment]
感謝，不過我三樓最多稱兩天，最晚一天就需要重新載人。我目前把ha定位關掉測試看看

**Comment by xzshow** [comment]
> 有遇到过类似问题，需要在HA重载集成才能好，不过出现频率不高（可能几周一次），暂时还没找到原因。
> 
> 我会开日志关注一下，看看下次出现的时候能不能找到线索

大佬我又来找您 了，我这一个小时不到全部不可用，等一下又好，然后又不可用，HA是core 2024.1.6版本的

**Comment by xzshow** [comment]
![Uploading 微信截图_20240203003725.png…]()

**Comment by xzshow** [comment]
![微信截图_20240203003750](https://github.com/rxwen/homeassistant-terncy-component/assets/110080681/f36d8607-6ba5-430a-a19c-c0d044f6761b)

**Comment by xzshow** [comment]
![Uploading 微信截图_20240203003725.png…]()

**Comment by xzshow** [comment]
![Uploading 微信截图_20240203003725.png…]()

**Comment by xzshow** [comment]
![Uploading 微信截图_20240203003725.png…]()

**Comment by Necroneco** [comment]
> > 有遇到过类似问题，需要在HA重载集成才能好，不过出现频率不高（可能几周一次），暂时还没找到原因。
> > 我会开日志关注一下，看看下次出现的时候能不能找到线索
> 
> 大佬我又来找您 了，我这一个小时不到全部不可用，等一下又好，然后又不可用，HA是core 2024.1.6版本的

我这还挺稳定的诶，我也是2024.1.6。
你是最近才这样的吗？网络方面或者其它有什么变化吗？

**Comment by xzshow** [comment]
我之前是老版本也没注意，昨晚才注意到的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2024年2月3日 13:27
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 透天環境，三樓網關一陣子會無回應 (Issue #57)





   
有遇到过类似问题，需要在HA重载集成才能好，不过出现频率不高（可能几周一次），暂时还没找到原因。
 我会开日志关注一下，看看下次出现的时候能不能找到线索
  
大佬我又来找您 了，我这一个小时不到全部不可用，等一下又好，然后又不可用，HA是core 2024.1.6版本的
  
我这还挺稳定的诶，我也是2024.1.6。
 你是最近才这样的吗？网络方面或者其它有什么变化吗？

**Comment by uho886** [comment]
我後來發現問題所在了，如果有用多網關融合，主網關那組設備會容易沒有回應。只要解除融合就穩定多了，你可以試看看

**Comment by xzshow** [comment]
我没有融合网关，哈是单个的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: uho886 ***@***.***&gt;
发送时间: 2024年2月3日 19:18
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 透天環境，三樓網關一陣子會無回應 (Issue #57)





 
我後來發現問題所在了，如果有用多網關融合，主網關那組設備會容易沒有回應。只要解除融合就穩定多了，你可以試看看

**Comment by rxwen** [comment]
如果还发现有问题，请试试这个版本： https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.39

**Comment by xzshow** [comment]
温总，这有几个开关一起这状态，现在都 不知道是那个开关了，房间和名称都 不同步
![1234](https://github.com/rxwen/homeassistant-terncy-component/assets/110080681/80fbd716-a2a3-420b-8300-4db5e830d408)

**Comment by xzshow** [comment]
![Uploading 1234.png…]()

**Comment by Necroneco** [comment]
> 温总，这有几个开关一起这状态，现在都 不知道是那个开关了，房间和名称都 不同步 ![1234](https://private-user-images.githubusercontent.com/110080681/302214581-80fbd716-a2a3-420b-8300-4db5e830d408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjA5NDAsIm5iZiI6MTcwNzEyMDY0MCwicGF0aCI6Ii8xMTAwODA2ODEvMzAyMjE0NTgxLTgwZmJkNzE2LWEyYTMtNDIwYi04MzAwLTRkYjVlODMwZDQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwODEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzQ1NWU1M2ZhYjE1NDMxOTkzZWVmMzA3N2FkNjc2ZGFjNDJkMTIzYzZhM2MzYzk0ZTJhMWI5MDhmZjVhY2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1_I_B0jDEmW-mst9T9cwtHeEfgwx7AS3dU91Oj28tAw)

这个嘛，应该是某个不到3路的开关的第3个按键。（现在这样确实不太好认）

**Comment by xzshow** [comment]
已确认了，是这东西，比如，不到4路的，上面有四个按键的，APP上有编码，要自己在HA中改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月5日(星期一) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 透天環境，三樓網關一陣子會無回應 (Issue #57)





  
温总，这有几个开关一起这状态，现在都 不知道是那个开关了，房间和名称都 不同步 
  
这个嘛，应该是某个不到3路的开关的第3个按键。（现在这样确实不太好认）

**Comment by xzshow** [comment]
我今天才发现门锁里面的电量是不变化的，一直是80，从来没变化 过

**Comment by rxwen** [comment]
> 如果还发现有问题，请试试这个版本： https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.40

先 close 此问题。如有问题再 open

**Comment by xzshow** [comment]
电量从来都是80没变过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rxwen ***@***.***&gt;
发送时间: 2024年2月24日 14:56
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 透天環境，三樓網關一陣子會無回應 (Issue #57)





  
如果还发现有问题，请试试这个版本： https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.40
  
先 close 此问题。如有问题再 open

**Comment by xzshow** [comment]
锁的电量从来都是80没变动过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rxwen ***@***.***&gt;
发送时间: 2024年2月24日 14:56
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 透天環境，三樓網關一陣子會無回應 (Issue #57)





  
如果还发现有问题，请试试这个版本： https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.40
  
先 close 此问题。如有问题再 open

**Comment by justzerock** [comment]
- Core 2024.3.3
- Supervisor 2024.03.1
- Operating System 12.1
- 前端 20240307.0

- terncy v1.0.40

我这边也是一样的问题，单个网关
实体在 HA 中时不时变成不可用

只能在集成中重载（我日常就靠定时重载任务解决，但总会遇上不可用状态）
不动HA，重启网关，无法解决这个问题

下面是日志：
<details><summary>Details</summary>
<p>

日志: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:239
集成: Home Assistant WebSocket API (文档, 问题)
首次发生: 22:11:00 (6 全部发生)
上次记录: 22:21:08

[139937861737024] sent 1000 (OK); no close frame received
[139937861736640] sent 1000 (OK); no close frame received
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 750, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/switch_as_x/entity.py", line 155, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/terncy/switch.py", line 78, in async_turn_on
    await self.api.set_attribute(
  File "/config/custom_components/terncy/core/gateway.py", line 224, in set_attribute
    ret = await self.api.set_attribute(eid, attr, value, method)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/terncy/terncy.py", line 321, in set_attribute
    await self._connection.send(json.dumps(data))
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received


</p>
</details>

**Comment by Necroneco** [comment]
很有帮助的日志, 看上去似乎是 HA 和网关之间的连接不太稳定.
我先简单 try catch 一下, 把这里的错误处理掉. 看看原本的重连机制还有没有效果.

你可以试试我的新 PR #63

**Comment by rxwen** [comment]
我在本地无法复现这个问题。请测试下这个1.0.41版本。
https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.41
