### ISSUE TITLE
这个项目还会一直更新吗？

### ISSUE THREAD

**Issue by tomcatGu** [rxwen/homeassistant-terncy-component#58]
听说小燕科技经营有问题了，这个项目还会一直更新吗？

**Comment by rxwen** [comment]
你好，这是个人和github上热心开发者维护的项目，不是小燕公司的。所以和小燕公司状态没有必然关系的。

**Comment by 1043717432** [comment]
还有一个问题。目前利用百灵网关接入到HA的，好像不是本地化。。如果百灵断网，那么HA里面也无法控制灯具，如果百灵网关断电，再恢复来电，HA没重启过。。所有小燕设备都无法使用。必须重启一次HA才可以！希望作者好心修复一下。多谢了！！
