### ISSUE TITLE
无线开关没有正确暴露

### ISSUE THREAD

**Issue by BerdyPango** [rxwen/homeassistant-terncy-component#60]
小燕的某些智能开关，例如凤凰，其开关组成分为开关(通断器)和无线开关。当在小燕 app 上启用无线开关时，没有正确的暴露给 HA。

配置如下所示：
![5e74c431d15b5dd354be45e95981114](https://github.com/rxwen/homeassistant-terncy-component/assets/13048793/c66b0be4-99d9-4f96-baec-716a8039e960)

**Comment by Necroneco** [comment]
按理应该是有的，你在HA看到的是什么样的呢？

---

方便的话，把调试日志发我看一下

> 在Terncy的集成页面点`启用调试日志`，然后`重载`一下

**Comment by xzshow** [comment]
小燕的门锁，电量在HA中永远是80，不会变动，这个有办法 吗？总是突然没电了不知道，在外面就傻B了

**Comment by xzshow** [comment]
他APP里面根本就没电量

**Comment by xzshow** [comment]
不然也可以在APP里面看了

**Comment by Necroneco** [comment]
> 他APP里面根本就没电量

那没办法了，一般来说这边也不会获得比app里更多的信息，你就当这个是不可用的吧。（这个门锁设备里还有其他实体是有用的吗？如果没有的话，之后HA里就不创建这个设备了）

**Comment by xzshow** [comment]
就只有开门关门的状态了，APp里面有开关，和管理钥匙管理，知道是谁开门，不知道HA能不能接进来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月8日(星期五) 上午9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxwen/homeassistant-terncy-component] 无线开关没有正确暴露 (Issue #60)





  
他APP里面根本就没电量
  
那没办法了，一般来说这边也不会获得比app里更多的信息，你就当这个是不可用的吧。（这个门锁设备里还有其他实体是有用的吗？如果没有的话，之后HA里就不创建这个设备了）

**Comment by Necroneco** [comment]
> 就只有开门关门的状态了，APp里面有开关，和管理钥匙管理，知道是谁开门，不知道HA能不能接进来

有开关门状态那还行。（别的没有就是没有的了）
电量嘛，别管它了，app里都没显示很可能说明它自己也测不准（80也许就是它目前自己认知的数值呢）

**Comment by BerdyPango** [comment]
为了保持每个 issue 的单一性，楼上的朋友可以单开一个 issue 讨论关于门锁电量的问题。

就无线开关没有暴露的问题，在我的 ios Home+6 app 是能看到的，举例来说。我有一个开关叫“客厅灯带”，在小燕 app 里启用了无线开关，在 HA 里看到的开关也正确反映了小燕 app 的设置：

![image](https://github.com/rxwen/homeassistant-terncy-component/assets/13048793/4460bf37-ffa2-4282-9933-8c6a2219455b)


但在启用无线开关，按理说多出一个实体，但在 HA 的实体列表l里面并没有出现这个实体：

![image](https://github.com/rxwen/homeassistant-terncy-component/assets/13048793/1ccae4e8-5b7b-4c0c-b9a9-40469573db47)

这4个实体，我没理解错的画，第1个是物理开关，后3个是开关的选项

**Comment by Necroneco** [comment]
是这样的，无线开关的本质是一个事件发射器，
目前有以下两种方式来监听这个变化：

1. 在设备页点击`自动化`区块右上角的➕，在这里可以看到设备事件`单击` `双击`等等。

    ![image](https://github.com/rxwen/homeassistant-terncy-component/assets/6160048/ddc2a98a-e7f9-4476-b05b-eb49eadcb350)

2. 你的HA版本是多少？如果HA版本>=2023.8，会创建一个 `event` 实体，具体用法可以参考HA文档 [1](https://www.home-assistant.io/blog/2023/08/02/release-20238/#introducing-the-event-entity) [2](https://www.home-assistant.io/integrations/event)（个人觉得目前不太好用，暂时推荐方案1）

    ![image](https://github.com/rxwen/homeassistant-terncy-component/assets/6160048/5290ac43-c373-45b9-9bd1-dd76787ab96e)

---

另外，这个事件其实无论有没有打开`启用无线开关`，都会有的。
