### ISSUE TITLE
HA导入小燕设备的实体ID

### ISSUE THREAD

**Issue by tomcatGu** [rxwen/homeassistant-terncy-component#62]

**Comment by tomcatGu** [comment]
为什么我导入的实体ID名称是类似于switch.terncy_943469fffe50cb6b_02，而不是拼音的命名形式？

**Comment by Necroneco** [comment]
各有各的好处吧，这种方式的名字是稳定的，即使删除集成后，在app里改了名，这边重新添加也还是这个名字。


可以考虑在添加集成的时候给一个选项，用自动生成的拼音名字

**Comment by rxwen** [comment]
我理解下，这是由于上一个无线开关的命名不够明确带进来的调整吗？

**Comment by Necroneco** [comment]
> 我理解下，这是由于上一个无线开关的命名不够明确带进来的调整吗？

不是，这是很久以前的改动，也只对那之后的新用户有效

如果觉得添加选项让用户自己决定这个方案可以的话，我后面几天有点空，可以看看好不好实现掉

**Comment by Necroneco** [comment]
找到问题原因了，应该是我在[这个位置](https://github.com/rxwen/homeassistant-terncy-component/commit/608454de4b5efa4de27b3bb929fb44cc096bb90b?diff=split&w=0#diff-cb6ed076bca2bc921234fadc62ec10b4d06be44a9ffc9d8581a53f554ea8ef58L495-R535)无意间引入的。

考虑了一下，我决定还原这个行为，拼音名字在实际情况下可能更好用一点。

**Comment by tomcatGu** [comment]
还有个问题，运行一段时间后窗帘设备会变为不可用，必须要重载后才能变为可用。

**Comment by Necroneco** [comment]
> 还有个问题，运行一段时间后窗帘设备会变为不可用，必须要重载后才能变为可用。

前几天的 [1.0.41](https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.41) 版本试过了吗？
是只有某一个窗帘，还是所有窗帘，还是网关下所有设备都不可用？

**Comment by tomcatGu** [comment]
> > 还有个问题，运行一段时间后窗帘设备会变为不可用，必须要重载后才能变为可用。
> 
> 前几天的 [1.0.41](https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.41) 版本试过了吗？ 是只有某一个窗帘，还是所有窗帘，还是网关下所有设备都不可用？

我还是用的1.0.38,没看到有更新的推送。是所有窗帘，其他设备还没注意。

**Comment by Necroneco** [comment]
> > > 还有个问题，运行一段时间后窗帘设备会变为不可用，必须要重载后才能变为可用。
> > 
> > 
> > 前几天的 [1.0.41](https://github.com/rxwen/homeassistant-terncy-component/releases/tag/v1.0.41) 版本试过了吗？ 是只有某一个窗帘，还是所有窗帘，还是网关下所有设备都不可用？
> 
> 我还是用的1.0.38,没看到有更新的推送。是所有窗帘，其他设备还没注意。

你可以在HACS打开`Show beta versions`的开关，装1.0.41试试。
光看代码看不出什么问题，由于我没有窗帘设备，所以也没法测试。

**Comment by rxwen** [comment]
窗帘是什么情况下出现离线的？还是始终显示离线的状态？
