### ISSUE TITLE
Expose Control for All LEDs on Terncy Wall Switches in Home Assistant

### ISSUE THREAD

**Issue by diegocjorge** [rxwen/homeassistant-terncy-component#65]
### Feature Request
**Summary:** Enable control of LED indicators on Terncy Wall Switches within Home Assistant, particularly when the switch is in wireless mode.

**Description:**
The Terncy app has introduced a feature that allows visual representation of scene activation status through the switch LED. This is particularly useful as it provides intuitive feedback to users by indicating whether a scene or device is active. The feature is detailed in their blog post (https://terncy.com/en-us/blog/posts/button_led_and_scene_activation_status/).

**Proposed Functionality:**
- Expose control for all button LEDs on Terncy Wall Switches in wireless mode within Home Assistant.
- Represent each button LED as an on/off toggle.
- If feasible, also expose the “power LED” on switches like the TERNCY-WS01 for on/off control.

**Use Cases:**
This feature would be beneficial in scenarios where the switch is in wireless mode and there's no direct visual feedback on the status of connected scenes or devices. By exposing LED control, users can incorporate them into automations, allowing for an easy and immediate understanding of their smart home setup’s state at a glance.

Additionally, also controlling the “power LED” would allow users to turn off the bright LED during sleep hours for a completely dark room. Currently, the Terncy app doesn't offer a way to automate this—it's either always on or always off.

Thank you for considering this feature request.

**Comment by rxwen** [comment]
This property isn't available in the communication protocol, so it's not achievable. But it can be done through in Terncy app.
Thanks for suggestion.
