### ISSUE TITLE
homeassistant core 2024.5.3 device can't find

### ISSUE THREAD

**Issue by ThunderLOG** [rxwen/homeassistant-terncy-component#69]
![屏幕截图 2024-05-16 003105](https://github.com/rxwen/homeassistant-terncy-component/assets/145313277/80cecb58-cc70-44a9-a919-90be7fa59e2c)
ha core 2024.5.3  无法自动搜索到家庭中心.
logs中 无相关信息

Thanks for help ，rxwen

**Comment by Necroneco** [comment]
HA和小燕网关在同一网段吗？

**Comment by ThunderLOG** [comment]
同一网段。之前HA2024.5.2 和terncy 1.0.41 适配没问题。 升级HA2024.5.3之后 1.0.41也能正常工作，昨日看到最新的1.0.44就想升级一下，换了包之后，就搜不到网关了。把网关恢复出厂设置也不行。。。

**Comment by Necroneco** [comment]
这倒挺奇怪的，我也都是最新版目前没什么问题。晚点我详细测试一下看看

**Comment by rxwen** [comment]
请问确定打开了插件的日志，没有任何信息？

**Comment by ThunderLOG** [comment]
log 中查到了terncy ，我看这个网关ip 10.0.0.107 已经识别到了

**Comment by rxwen** [comment]
报错的那行好像和这个插件无关吧，是其他插件报出来的？


Regards,
Ruixiong Wen


ThunderLOG ***@***.***>于2024年5月16日 周四13:39写道：

**Comment by rxwen** [comment]
用 2024.5.3 版本ha，搭配 1.0.44 版本的插件，测试没出现问题。控制正常。

**Comment by tomcatGu** [comment]
自动化执行的时候，窗帘状态不可用，是怎么回事？但是窗帘在界面上是可以控制的。
以下是日志：
2024年5月28日
日出打开窗帘 sunrise with offset
05:21:43 - 5小时前
西南卧窗帘 不再可用 由自动化触发 日出打开窗帘 sunrise with offset
05:21:43 - 5小时前
西南卧窗帘 已打开 由自动化触发 日出打开窗帘 sunrise with offset
05:21:46 - 5小时前
西南卧窗帘 已关闭 由自动化触发 日出打开窗帘 sunrise with offset
05:21:46 - 5小时前

**Comment by Necroneco** [comment]
> 自动化执行的时候，窗帘状态不可用，是怎么回事？但是窗帘在界面上是可以控制的。 以下是日志： 2024年5月28日 日出打开窗帘 sunrise with offset 05:21:43 - 5小时前 西南卧窗帘 不再可用 由自动化触发 日出打开窗帘 sunrise with offset 05:21:43 - 5小时前 西南卧窗帘 已打开 由自动化触发 日出打开窗帘 sunrise with offset 05:21:46 - 5小时前 西南卧窗帘 已关闭 由自动化触发 日出打开窗帘 sunrise with offset 05:21:46 - 5小时前

看上去似乎只是中间有一瞬间不可用。实际最后窗帘被打开了吗？
集成版本是昨天的1.0.47还是之前的版本？
只在自动化里会有问题吗？手动控制是完全正常的，也不会出现 不再可用 的日志？
自动化里打开窗帘调用的是哪个指令？是`service: cover.open_cover`？还是通过设备里的动作？用的是`open`还是`set_position: 100`？

**Comment by tomcatGu** [comment]
没有打开。手动是正常的。用的open_cover指令。

**Comment by Necroneco** [comment]
方便的话，打开调试，再触发一下自动化看看日志

**Comment by tomcatGu** [comment]
手动触发自动化是正常的。

**Comment by Necroneco** [comment]
这个每天都会这样吗？还是偶尔一次？
我猜可能那时候已经断线了。你如果没重启过HA的话，去系统日志里看一下 05:21 附近有没有 terncy 的重连日志

**Comment by tomcatGu** [comment]
日志: custom_components.terncy.core.gateway
来源: custom_components/terncy/core/gateway.py:158
集成: Terncy
首次发生: 2024年5月21日 20:39:24 (10 全部发生)
上次记录: 05:21:45

Reconnect terncy service: box-1c-82-59-90-14-46 {'dev_id': 'box-1c-82-59-90-14-46'} after wait

**Comment by tomcatGu** [comment]
是这个吗？

**Comment by tomcatGu** [comment]
最好能提供个reload服务，可以每天定时重载下terncy

**Comment by Necroneco** [comment]
嗯 那就是了，HA和小燕网关之间的连接掉了，直到自动化去执行的时候它才发现，然后才重连。

这块是可以再优化一下，不过具体方案还要再考虑考虑。

---

定时重载也是个办法，可以临时解决一下。HA自带有这个功能的，调这个服务就行：
```yaml
service: homeassistant.reload_config_entry
data:
  entry_id: c0e4213f26f11a9bbc4664a7efbbf26b
```

![image](https://github.com/rxwen/homeassistant-terncy-component/assets/6160048/2e0f8bea-04a8-4a02-8762-3770af6102e6)

这个 entry_id 的话，点这里进去，然后看网址 &config_entry= 后面的部分就是

**Comment by rxwen** [comment]
有完整的日志吗？想看看什么时候发生断连的。

Regards,
Ruixiong Wen


Necroneco ***@***.***>于2024年5月28日 周二11:39写道：

**Comment by rxwen** [comment]
Close for idle too long.
