### ISSUE TITLE
Terncy Devices/Entities Domain

### ISSUE THREAD

**Issue by mygithandle** [rxwen/homeassistant-terncy-component#7]
After integration, Terncy device Entities all show in HA under HA Domain Light, regardless of light or switch..

I have many Terncy wall switches (4gang, 3,  2, and singles). All show up in HA entity list as Light.[devID]

Is this normal? Or is there a way to force switches to integrate as Switch.[ID] ?

Also, is there any documentation to show how device settings in Terncy app map to HA settings ?

Thanks

**Comment by rxwen** [comment]
Yes, based on what I learn, there is no easy way to distinguish between light and switch right now.

The only setting will affect the device shown in HA is the programmable switch. Others are not relevant now.

**Comment by rxwen** [comment]
Solved in 1.0.12

**Comment by mygithandle** [comment]
Thanks. 
will redo the integration with 1.0.14
