### ISSUE TITLE
关于小燕门锁要需求

### ISSUE THREAD

**Issue by xzshow** [rxwen/homeassistant-terncy-component#77]
在小燕APP中能分辨指纹，不知道大佬能否装指纹接入到HA，这锁在HA中太浪费了，目前我没法只能在APP中套娃开头或者灯来联动某人开锁，请大佬接入下，感激

**Comment by Necroneco** [comment]
之前好像确认过，局域网协议里目前只有这点信息，没有指纹之类的细节。

**Comment by xzshow** [comment]
是的，温总应该能搞定啦，哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Necroneco ***@***.***&gt;
发送时间: 2024年9月10日 13:14
收件人: rxwen/homeassistant-terncy-component ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [rxwen/homeassistant-terncy-component] 关于小燕门锁要需求 (Issue #77)





 
之前好像确认过，局域网协议里目前只有这点信息，没有指纹之类的细节。

**Comment by Necroneco** [comment]
嗯 你说得对 找他能搞得定~

**Comment by xzshow** [comment]
#
![Uploading 微信截图_20240910160410.png…]()

**Comment by Necroneco** [comment]
> 大佬找下咯，搞个福利

这你自己找咯~

**Comment by Necroneco** [comment]
> 还有我插件长到最新的，为什么小燕图标下面还是1.0.42呀，是不是有什么问题？

问题不大，只是版本号忘记改了

**Comment by rxwen** [comment]
这个功能受限与协议了
